import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Appbar from "./components/Appbar";
import { Toaster } from 'sonner';

import {
  ClerkProvider
} from '@clerk/nextjs'
import Provider from "./components/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "600"], // or any weights you plan to use
  subsets: ["latin"],
}); 


export const metadata: Metadata = {
  title: "Naachogaao - The best way to find your next ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <ClerkProvider dynamic>
      <html lang="en" suppressHydrationWarning={true}>
        <body
          className={`${poppins.className} antialiased transition-colors duration-300`}
          data-theme="dark"
          style={{ background: "var(--bg)", color: "var(--text-primary)" }}
          >  
            <Toaster />
            <Provider>
            <div className="">
              <Appbar/>
              {children}      
            </div>
            </Provider>     
        </body>
      </html>
    </ClerkProvider>
  );
}
